name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build package
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add zip
            l3build ctan
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: sjtubeamermin-ctan.zip